version: "3.9"  # optional since v1.27.0
services:
  ctf:
    container_name: kalictf
    image: cottontail/ctf:latest
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    init: true
    build:
      context: "."
      dockerfile: kalictf.Dockerfile
    tty: true
    user: "1000:1000"
    ports:
      - "127.0.0.1:3390:3390"
    volumes:
      - /home/cottontail/Tools:/home/ctf/tools:rw
      - kalictfdata:/mnt/ctfs
volumes:
  kalictfdata: {}